# Generated by Django 6.0.6 on 2026-07-06 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('first class', 'Birinchi dars'), ('viewed', "Ko'rilgan"), ('coming', 'Aniq keladi'), ('cancel', 'Rad etdi'), ('student', "O'quvchi")], default='new', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ClientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.client')),
            ],
            options={
                'verbose_name_plural': 'Client Histories',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=100)),
                ('monthly_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_reminder_sent', models.DateField(blank=True, help_text='Oxirgi marta Telegram orqali eslatma yuborilgan sana (takror yuborilmasligi uchun)', null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='lead.client')),
            ],
        ),
    ]
